---
# Breaks reusing MD snippets extracted to files
first-line-heading: false

# Set maximum line Length to 140c to match Go linting
line-length:
  line_length: 140

# Allow HTML span elements to set font sizes
no-inline-html:
  allowed_elements:
    - span

# Temporary while helm-docs has a bug where maintainer URLs are used raw in MD
# Waiting on: https://github.com/norwoodj/helm-docs/pull/102
no-bare-urls: false
